version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ChecksAndBalances
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 200
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 100
      runas: root
