POST http://localhost:5001/api/login
content-type: application/json

{
    "username": "RickL",
    "password": "COP4331"
}
###
POST https://checksnbalances.us/api/login
content-type: application/json

{
    "username": "1",
    "password": "1"
}
###
POST http://localhost:5001/api/register
content-type: application/json

{
    "username": "RickL",
    "password": "COP4331",
    "email": "Richard.Leinecker@ucf.edu",
    "firstName": "Rick",
    "lastName": "Leinecker",
    "address": "4000 Central Florida Blvd, Orlando, FL",
    "zipCode": "32816"
}
###
POST http://localhost:5001/api/login HTTP/1.1
content-type: application/json

{
    "username": "username",
    "password": "password"
}
###
POST http://localhost:5001/api/register
content-type: application/json

{
    "username": "username",
    "password": "password",
    "email": "junidyeom@gmail.com",
    "firstName": "Username",
    "lastName": "Password",
    "address": "4000 Central Florida Blvd, Orlando, FL",
    "zipCode": "32816"
}
###
POST http://localhost:5001/api/login
content-type: application/json

{
    "username": "fhadsjkfdsjklfdasjof",
    "password": "dhfodshfudsahfiup"
}
###
POST http://localhost:5001/api/login
content-type: application/json

{
    "username": "gWash89",
    "password": "firstPresident"
}

###
POST https://checksnbalances.us/api/getSenByState
content-type: application/json

{
    "state": "nj"
}

###
POST https://checksnbalances.us/api/getRepByDistrict
content-type: application/json

{
    "id": 11,
    "state": "fl"
}
###
POST http://localhost:5001/api/getSenByState
content-type: application/json

{
    "state": "fl"
}
###
POST https://checksnbalances.us/api/login
content-type: application/json

{
    "username": "gWash89",
    "password": "firstPresident"
}
###
GET http://localhost:5001/api/readInterests?userId=65580d043bdf8a775970f892
###
GET http://localhost:5001/api/readInterests?65580d043bdf8a775970f892
###
GET http://localhost:5001/api/readInterests
###
GET http://localhost:5001/api/geocode?address=213%20Meadow%20Wood%20Drive&state=Alabama
###
GET http://localhost:5001/api/getDistrict?coords=%5B27%2C%20-82%5
###
POST http://localhost:5001/api/register
content-type: application/json

{
    "email": "licexi6187@cumzle.com",
    "password": "password",
    "address": "4000 Central Florida Blvd, Orlando, FL",
    "interests": [
        {"InterestName": "Agriculture", "value": true},
        {"InterestName": "Spending", "value": false},
        {"InterestName": "Military & National Defense", "value": false},
        {"InterestName": "Veterans", "value": false},
        {"InterestName": "Taxation", "value": false},
        {"InterestName": "Finance", "value": false},
        {"InterestName": "Education", "value": false},
        {"InterestName": "Labor", "value": true},
        {"InterestName": "Energy", "value": false},
        {"InterestName": "Science & Technology", "value": false},
        {"InterestName": "Governmental Reform", "value": false},
        {"InterestName": "Foreign Affairs", "value": true},
        {"InterestName": "Infrastructure", "value": false},
        {"InterestName": "Health", "value": false}
    ]
}
###
POST http://localhost:5001/api/login
content-type: application/json

{
    "email": "Tester2@test.com",
    "password": "!Test123"
}
###
GET http://localhost:5001/api/getUser?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjY4Mjk1OWFmZGY5ODc5NDljY2NmZSIsImZpcnN0TmFtZSI6IlRlc3QyIiwibGFzdE5hbWUiOiJUZXN0MiIsInBhc3N3b3JkIjoiIVRlc3QxMjMiLCJlbWFpbCI6IlRlc3RlcjJAdGVzdC5jb20iLCJhZGRyZXNzIjoiNDAwMCBDZW50cmFsIEZsb3JpZGEgQmx2ZC4gT3JsYW5kbywgRkwgMzI4MTYiLCJpYXQiOjE3MDEyOTEzOTAsImV4cCI6MTcwMTM3Nzc5MH0.h8_LeAOtijRDkuHmHfJgy4mbJ-JnEwyXueHGi06gHqc
###
POST http://localhost:5001/api/searchBillsBasic
content-type: application/json

{
    "input": "emissions"
}